version: '3'

services:
  web:
    build: .
    command: python brendwall/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/brendwall_app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=brendwall.settings